FROM fedora:32

RUN groupadd prometheus
RUN useradd -g prometheus prometheus

RUN dnf install -y wget
RUN wget -O prometheus.tar.gz https://github.com/prometheus/prometheus/releases/download/v2.18.1/prometheus-2.18.1.linux-amd64.tar.gz
RUN tar xf prometheus.tar.gz
RUN mv prometheus-2.18.1.linux-amd64 /app
RUN chown -R prometheus: /app
RUN chown -R prometheus: /var/lib/prometheus
RUN chown -R prometheus: /etc/prometheus

ENV PATH="$PATH:/app"

COPY run-prometheus.sh /app/run.sh

EXPOSE 9091
USER prometheus
WORKDIR /var/lib/prometheus
ENTRYPOINT [ "/app/run.sh" ]
