global:
  scrape_interval:     15s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'cthuloo.rlyeh.local:9091' ]

  - job_name: 'grafana'
    static_configs:
      - targets: [ 'cthuloo.rlyeh.local:3000' ]

  - job_name: 'cthuloo'
    static_configs: 
      - targets: [ 'cthuloo.rlyeh.local:9100' ]

  - job_name: 'nyarly'
    static_configs: 
      - targets: [ 'nyarly.rlyeh.local:9100' ]

  - job_name: 'hosts'
    static_configs:
      - targets: [ 'dagoon.rlyeh.local:9100'
                 , 'nyarly.rlyeh.local:9100'
                 , 'cthuloo.rlyeh.local:9100'
                 ]
