FROM fedora:32

RUN dnf install -y wget

RUN groupadd grafana
RUN useradd grafana -g grafana

RUN wget -O grafana.tar.gz https://dl.grafana.com/oss/release/grafana-6.7.3.linux-amd64.tar.gz
RUN tar xf grafana.tar.gz
RUN mv grafana-6.7.3 g

ENV GF_PATHS_CONFIG_DIR="/etc/grafana"                  \
    GF_PATHS_CONFIG="$GF_PATHS_CONFIG_DIR/grafana.ini"  \
    GF_PATHS_DATA="/var/lib/grafana"                    \
    GF_PATHS_HOME="/g"                  \
    GF_PATHS_LOGS="/var/log/grafana"                    \
    GF_PATHS_PLUGINS="/var/lib/grafana/plugins"         \
    GF_PATHS_PROVISIONING="/etc/grafana/provisioning"   \
    PATH="$PATH:/g/bin"


RUN mkdir -p "$GF_PATHS_HOME/.aws"
RUN mkdir -p "$GF_PATHS_PROVISIONING/datasources"         \
             "$GF_PATHS_PROVISIONING/dashboards"          \
             "$GF_PATHS_PROVISIONING/notifiers"           \
             "$GF_PATHS_LOGS"                             \
             "$GF_PATHS_PLUGINS"                          \
             "$GF_PATHS_CONFIG_DIR"                       \
             "$GF_PATHS_DATA"

RUN          cp /g/conf/sample.ini "$GF_PATHS_CONFIG"
RUN          cp /g/conf/ldap.toml "$GF_PATHS_CONFIG_DIR"
RUN          chown -R grafana:grafana "$GF_PATHS_DATA" "$GF_PATHS_HOME" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING"
RUN          chmod -R 777 "$GF_PATHS_DATA" "$GF_PATHS_HOME" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING"

COPY run-grafana.sh /usr/sbin/run-grafana.sh

EXPOSE 3000

WORKDIR $GF_PATHS_HOME
USER grafana
ENTRYPOINT [ "/usr/sbin/run-grafana.sh" ]
