FROM fedora:32

RUN groupadd prometheus
RUN useradd -g prometheus prometheus

RUN dnf install -y wget
RUN wget -O alertmanager.tar.gz https://github.com/prometheus/alertmanager/releases/download/v0.20.0/alertmanager-0.20.0.linux-amd64.tar.gz

RUN tar xf alertmanager.tar.gz
RUN mv alertmanager-0.20.0.linux-amd64 app
COPY run-alertmanager.sh /app/run.sh
RUN chown -R prometheus:prometheus /app /etc/alertmanager/

EXPOSE 9093
USER prometheus
WORKDIR /app
ENTRYPOINT [ "/app/run.sh" ]
